[project]
name = "casino-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "scrapy>=2.12.0",
    "sqlalchemy>=2.0.40",
]
